project_id = "gpoiffvtkhblcohmelha"

[functions.shipstation-sync]
verify_jwt = false

[functions.shipstation-webhook]
verify_jwt = false

[functions.shipstation-api]
verify_jwt = false

[functions.send-order-notification]
verify_jwt = false

[functions.send-wholesale-status-email]
verify_jwt = false